---
name: Hello World

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: container-runner
# renovate: datasource=endoflife-date packageName=fedora versioning=docker
    container: quay.io/fedora/fedora:36
    steps:
      - run: echo "Hello World"
